ceph-luminous: build against python27
reason
======

**summary:** While for most components of ceph 12.x there are Python3 bindings
available, `ceph-mgr` only builds against python2.7. Thus sticking to
that single python version is the simplest choice.

**details:**

> @John, we only just started compiling MGR with Python 3. The current status is that it builds. Working is another matter.
https://tracker.ceph.com/issues/22880

The [fix](https://github.com/ceph/ceph/pull/20362) supposed to make ceph-mgr actually work with python3 is, [according to GitHub, only part of v13.0.2 and following.](https://github.com/ceph/ceph/pull/20362/commits/ba82060deffc21dc38736dad5c19731162cbc906)
This suggests that ceph-mgr might not work when built against python3.

And even when it comes to building, currently the ceph build fails both with python-3.6 as well as python-3.8 with the following error:

```
/build/source/src/mgr/PyFormatter.cc: In member function 'virtual void PyFormatter::dump_string(const char*, boost::string_view)':
/build/source/src/mgr/PyFormatter.cc:60:23: error: 'PyString_FromString' was not declared in this scope; did you mean 'PyLong_FromString'?
   60 |   dump_pyobject(name, PyString_FromString(s.data()));
      |                       ^~~~~~~~~~~~~~~~~~~
      |                       PyLong_FromString
Scanning dependencies of target unittest_admin_socket
/build/source/src/mgr/PyFormatter.cc: In member function 'virtual void PyFormatter::dump_format_va(const char*, const char*, bool, const char*, __va_list_tag*)':
/build/source/src/mgr/PyFormatter.cc:93:23: error: 'PyString_FromString' was not declared in this scope; did you mean 'PyLong_FromString'?
   93 |   dump_pyobject(name, PyString_FromString(buf));
      |                       ^~~~~~~~~~~~~~~~~~~
      |                       PyLong_FromString
/build/source/src/mgr/PyFormatter.cc: In member function 'void PyFormatter::dump_pyobject(const char*, PyObject*)':
/build/source/src/mgr/PyFormatter.cc:105:21: error: 'PyString_FromString' was not declared in this scope; did you mean 'PyLong_FromString'?
  105 |     PyObject *key = PyString_FromString(name);
      |                     ^~~~~~~~~~~~~~~~~~~
      |                     PyLong_FromString
/build/source/src/mgr/PyFormatter.cc: In member function 'void PyFormatter::finish_pending_streams()':
/build/source/src/mgr/PyFormatter.cc:121:9: error: 'PyString_FromString' was not declared in this scope; did you mean 'PyLong_FromString'?
  121 |         PyString_FromString(i->stream.str().c_str()));
      |         ^~~~~~~~~~~~~~~~~~~
      |         PyLong_FromString
```

When looking up the function `PyString_FromString` at https://docs.python.org/, it is only found in the python2 docs but in none of python 3.5 or above.

Looking at the [Debian packaging](https://github.com/ceph/ceph/blob/v12.2.13/debian/control) of Luminous, ceph-mgr still depends on python2 there although several additional python3 bindings to rbd and rgw are provided as well.

Of course I tried the additionam configure flags `-DMGR_PYTHON_VERSION=3 -DWITH_PYTHON2=OFF -DWITH_PYTHON3=ON` mentioned in the ceph-mrg python3 ticket, but they do not fix this issue as `MGR_PYTHON_VERSION` is not found in the Luminous code.

Instead, the CMake config for ceph-mgr [clearly indicates that it is python2 only in Luminous](https://github.com/ceph/ceph/blob/v12.2.13/CMakeLists.txt#L447):

```cmake
option(WITH_MGR "ceph-mgr is enabled" ON)
if(WITH_MGR)
    set(Python_ADDITIONAL_VERSIONS 2.7)
    find_package(PythonInterp 2.7 REQUIRED)
    find_package(PythonLibs 2.7 REQUIRED)
    # Boost dependency check deferred to Boost section
endif(WITH_MGR)
```

----

requires vendoring of a lot of python27 packages to backport them to the
last version support python-2.7:

- cheroot
- cherrypy
- jaraco_text
- pecan
- portend
- pypytools
- pyquery
- tempora
- waitress
- webtest
- zc_lockfile

Additionally, tests for the following python2 packages needed to be
disabled:

- routes
- webtest
- zc_lockfile
- cherrypy

zc_lockfile has issues with test case discovery, all other cases of
disabling tests are due to failing imports of modules containing a "."
in their name.