Revert "Merge pull request #845 from flyingcircusio/PL-131630-host-vxlan-support"
This reverts commit bc58d2f59d27806e31ada6885a4c79c00a16bdfc, reversing
changes made to 70f45a29cdae26bc2ce2d323f700a81943f4b639.

For some reason this PR was broken but didn't get caught properly or
missed in the Github PR UI.

a) hydra doesn't properly evaluate the 23.05 module import
b) at least the postgresql test fails with

       error: attribute 'policy' missing

       at /home/ctheune/fc-nixos/nixos/lib/network.nix:20:55:

           19|       underlayCount = length (attrNames underlayInterfaces);
           20|       vxlanInterfaces = lib.filterAttrs (name: value: value.policy == "vxlan") encInterfaces;
             |                                                       ^
           21|       vxlanCount = length (attrNames vxlanInterfaces);