tests.channel: remove failing nix-env -qa subtest
The subtest turns out to be very brittle in NixOS-test-vms. In this
particular case, it fails due to the newly imported additional
nixpkgs-22_11 channel:

error: cannot import '/nix/store/2q3dd73ppbj5wka16dvnjqfak347xmfv-nixpkgs-22.11-6a70ea11060', since path '/nix/store/y1z2pm89yya6a5qnjsvp0d7369h3z05f-nixpkgs-22.11-6a70ea11060.drv' is not valid, at /nix/store/j0aav96lqhxl7fjz8126ixcmkzbyv6v3-fc-overlay/pkgs/overlay.nix:12:19

The derivation file for that channel was not pulled into the closure of
the VM but is required for evaluation by nix-env.

As @dpausp and I did not really manage to reliably pull that derivation
file in, we have decided to remove the subtest and replace it with a
periodic sensu check on a testvm.