services/redis: fix case with no password and Unix socket
PL-133563

This case wasn't covered by the redis test and I wrongly assumed that
Telegraf would be evaluated by the GitLab test which is why this got
missed.

If no password is set for a non-default Redis server, the `password` is
null leading to an eval-error like this:

    error: A definition for option `services.telegraf.extraConfig.inputs.redis."[definition 1-entry 2]".password' is not of type `TOML value'. Definition values:
    - In `/nix/store/yf7zp3p32f24ak5rrpzsgmb521z2wncq-source/fc/nixos/services/telegraf': null